name: phpstan
on:
  pull_request
jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: "get creator of pull request to except from reviewer"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo `gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files | jq -c '.[].filename'`
      - name: "get creator of pull request to except from reviewer"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "files=.github/workflows/phpstan.yml aaa.tzt" >> $GITHUB_ENV
      - name: "get creator of pull request to except from reviewer"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "files=`gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files | jq -c '.[].filename' | xargs`" >> $GITHUB_ENV
      - name: echo env.files
        run: echo ${{ env.files }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.1'
          tools: phpstan


      - uses: actions/checkout@v3
      - run: composer require phpstan/phpstan
      - run: pwd
      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse --memory-limit=3G ${{ env.files }}

