name: Create Pull Reqeust for release
on: 
  push:
    branches:
      - 'develop'
jobs:
  gh-pr-create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ff
        if: gh pr list --base main --head develop | awk '{print $3}' != 'develop'
        run: gh pr create --head develop --base main --title Release`date "+%Y%m%d"` --body 'This is pull request for release.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
