name: Create Pull Reqeust for release
on: 
  push:
    branches:
      - 'develop'
jobs:
  gh-pr-create:
    runs-on: ubuntu-latest
    steps:
      - run: gh pr create --head develop --base main --title Release`date "+%Y%m%d"` --body 'This is pull request for release.'
      
